backend:
  name: git-gateway
  repo: ollyrofl/loanstudio
  branch: main
  identity_url: https://auth.decapbridge.com/sites/54290cb8-3ee8-4795-b68a-9e51e1f2f563
  gateway_url: https://gateway.decapbridge.com
  commit_messages:
    create: Create {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} "{{slug}}" - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete "{{path}}" - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

logo_url: https://decapbridge.com/decapcms-with-bridge.svg
site_url: https://loanstudio.netlify.app

media_folder: "images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string", required: false}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Thumbnail Image", name: "thumbnail", widget: "image"}
      - {label: "Summary", name: "summary", widget: "text"}
      - {label: "Body", name: "body", widget: "markdown"}
